In [3]:
import numpy as np
import tensorflow as tf
from tensorflow import keras

In [14]:
training_datagen = keras.preprocessing.image.ImageDataGenerator(rescale = 1/255.0,
                                                                shear_range = 0.2,
                                                                horizontal_flip = True)

training_data = training_datagen.flow_from_directory("/content/drive/MyDrive/Data Sets/koala_lion_Classification/train",
                                                     target_size = (180,180),
                                                     batch_size = 32,
                                                     class_mode = 'binary')

testing_datagen = keras.preprocessing.image.ImageDataGenerator(rescale = 1/255)

testing_data = testing_datagen.flow_from_directory("/content/drive/MyDrive/Data Sets/koala_lion_Classification/test",
                                                    target_size = (180,180),
                                                     batch_size = 32,
                                                     class_mode = 'binary')

Found 144 images belonging to 2 classes.
Found 37 images belonging to 2 classes.


In [15]:
pre_trained_model = keras.applications.vgg16.VGG16(include_top = False,
weights = 'imagenet',
input_shape = (180,180,3),
pooling = 'avg',
classes = 2)

for layers in pre_trained_model.layers:
  layers.trainable = False  


In [16]:
model = keras.Sequential()
model.add(pre_trained_model)
model.add(keras.layers.Flatten())
model.add(keras.layers.Dense(128, activation = 'relu'))
model.add(keras.layers.Dense(1, activation = 'sigmoid'))
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 vgg16 (Functional)          (None, 512)               14714688  
                                                                 
 flatten_1 (Flatten)         (None, 512)               0         
                                                                 
 dense_2 (Dense)             (None, 128)               65664     
                                                                 
 dense_3 (Dense)             (None, 1)                 129       
                                                                 
Total params: 14,780,481
Trainable params: 65,793
Non-trainable params: 14,714,688
_________________________________________________________________


In [17]:
model.compile(optimizer = 'Adam',
              loss = 'binary_crossentropy',
              metrics = ['accuracy'])

model.fit(training_data,
          epochs = 5,
          validation_data = testing_data)

Epoch 1/5
5/5 [==============================] - 60s 12s/step - loss: 0.6325 - accuracy: 0.6250 - val_loss: 0.6402 - val_accuracy: 0.5135
Epoch 2/5
5/5 [==============================] - 58s 12s/step - loss: 0.5730 - accuracy: 0.6042 - val_loss: 0.5248 - val_accuracy: 0.8378
Epoch 3/5
5/5 [==============================] - 57s 12s/step - loss: 0.4722 - accuracy: 0.8403 - val_loss: 0.4892 - val_accuracy: 0.8378
Epoch 4/5
5/5 [==============================] - 59s 12s/step - loss: 0.4190 - accuracy: 0.8889 - val_loss: 0.4402 - val_accuracy: 0.8378
Epoch 5/5
5/5 [==============================] - 57s 12s/step - loss: 0.3587 - accuracy: 0.9583 - val_loss: 0.4178 - val_accuracy: 0.8108


In [20]:
image_array = keras.preprocessing.image.load_img("/content/drive/MyDrive/Data Sets/koalabhai.jfif",
                                                 target_size = (180,180))
image_array = keras.preprocessing.image.img_to_array(image_array)
print(image_array)
image_array = np.expand_dims(image_array, axis = 0)
print(image_array.shape)
if model.predict(image_array) > 0.5:
  print("Lion mama")
else:
  print("Koala anna")

[[[119. 125. 121.]
  [135. 144. 141.]
  [145. 155. 154.]
  ...
  [195. 210. 181.]
  [182. 198. 159.]
  [168. 188. 135.]]

 [[124. 130. 126.]
  [141. 147. 143.]
  [149. 158. 157.]
  ...
  [181. 196. 165.]
  [173. 190. 148.]
  [173. 193. 140.]]

 [[133. 140. 133.]
  [144. 150. 146.]
  [148. 157. 154.]
  ...
  [171. 185. 150.]
  [160. 177. 133.]
  [168. 186. 136.]]

 ...

 [[ 74. 102.  54.]
  [ 73. 102.  56.]
  [ 76. 107.  65.]
  ...
  [118. 132. 115.]
  [109. 124. 105.]
  [107. 125. 103.]]

 [[ 73. 100.  59.]
  [ 78. 105.  64.]
  [ 84. 114.  76.]
  ...
  [116. 131. 112.]
  [106. 121. 100.]
  [102. 120.  96.]]

 [[ 82. 106.  72.]
  [ 79. 105.  70.]
  [ 82. 109.  76.]
  ...
  [108. 123. 102.]
  [ 99. 114.  91.]
  [ 96. 114.  88.]]]
(1, 180, 180, 3)
1/1 [==============================] - 0s 325ms/step
Koala anna


# New Section